sudo: required
services:
  - docker

before_install:
  - docker build -t virajyerunkar007/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run virajyerunkar007/react-test npm test -- --coverage

after_success:
  - docker build -t virajyerunkar007/multi-client ./client
  - docker build -t virajyerunkar007/multi-nginx ./nginx
  - docker build -t virajyerunkar007/multi-server ./server
  - docker build -t virajyerunkar007/multi-worker ./worker

  - echo "DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push virajyerunkar007/multi-client
  - docker push virajyerunkar007/multi-nginx
  - docker push virajyerunkar007/multi-server
  - docker push virajyerunkar007/multi-worker
